version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    container_name: devly_db
    environment:
      POSTGRES_USER: devly
      POSTGRES_PASSWORD: devly123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - local-network

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./front:/usr/share/nginx/app"
      - "./front/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - local-network
    depends_on:
      - back

  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    networks:
      - local-network
    ports:
      - "8080:8080"
    depends_on:
      - back
    platform: linux/amd64

  back:
    build:
      context: .
      dockerfile: ./back/Devly/Devly.Host/Dockerfile
    container_name: back
    networks:
      - local-network
    environment:
      "ConnectionStrings__Postgres" : "Host=postgres;Port=5432;User Id=devly;Password=devly123;Database=postgres;"
    ports:
      - "80:80"
    depends_on:
      - postgres

networks:
  local-network:
    driver: bridge
