version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    container_name: devly_db
    environment:
      POSTGRES_USER: devly
      POSTGRES_PASSWORD: devly123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - local-network

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./front:/usr/share/nginx/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - local-network
        
  back:
    build:
      context: .
      dockerfile: ./back/Devly/Devly.Host/Dockerfile
    container_name: back
    networks:
      - local-network
    ports:
      - "80:80"
    depends_on:
      - postgres

networks:
  local-network:
    driver: bridge
