version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    container_name: devly_db
    environment:
      POSTGRES_USER: devly
      POSTGRES_PASSWORD: devly123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
