version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    container_name: devly_db
    environment:
      POSTGRES_USER: devly
      POSTGRES_PASSWORD: devly123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - local-network
  
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back
    networks: 
      - local-network
    ports:
      - "80:80"
    depends_on: 
      - postgres

networks:
  local-network:
    driver: bridge
